AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  nextbus-api

  Sample SAM Template for nextbus-api
  
Globals:
  Function:
    Timeout: 10

Resources:
  NextbusFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: nextbusAPI/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      MemorySize: 128
      Description: 'Lambda function to get nextBusMap '
      Events:
        NextbusAPI:
          Type: Api 
          Properties:
            Path: /*
            Method: get
